Se desea obtener mediante **cálculo simbólico** la versión lineal del péndulo en el equilibrio inestable.
Se emplea Taylor previo reemplazo de cos(𝛷) ≈1 y sen(𝛷)≈𝛷.
Luego se presenta el sistema matricial.

In [1]:
!apt install octave

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  aglfn epstool fonts-droid-fallback fonts-noto-mono ghostscript gnuplot-data
  gnuplot-qt gsfonts imagemagick-6-common info install-info libamd2
  libauthen-sasl-perl libcamd2 libccolamd2 libcholmod3 libcolamd2
  libcupsfilters1 libcupsimage2 libcxsparse3 libdata-dump-perl libemf1
  libencode-locale-perl libfftw3-single3 libfile-listing-perl libfltk-gl1.3
  libfltk1.3 libfont-afm-perl libgail-common libgail18 libglpk40
  libgraphicsmagick++-q16-12 libgraphicsmagick-q16-3 libgs9 libgs9-common
  libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libhtml-form-perl
  libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-mess

In [2]:
!apt install octave-symbolic

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  ipython javascript-common libjs-jquery libjs-sphinxdoc libjs-underscore
  python-backports-shutil-get-terminal-size python-chardet python-configparser
  python-decorator python-enum34 python-future python-gmpy python-ipython
  python-ipython-genutils python-mpmath python-olefile python-pathlib2
  python-pexpect python-pickleshare python-pil python-pkg-resources
  python-prompt-toolkit python-ptyprocess python-pyglet python-pygments
  python-scandir python-simplegeneric python-six python-sympy python-traitlets
  python-wcwidth
Suggested packages:
  apache2 | lighttpd | httpd python-enum34-doc python-future-doc
  python-gmpy-doc python-gmpy2 python-matplotlib python-mpmath-doc
  python-pexpect-doc python-pi

Se debe agregar en el .m el path donde está el Python, mediante una línea como ésta:

---


**setenv PYTHON /usr/bin/python**


---


para acceder al sympy desde symbolic. No obtante, puede ser diferente el path y debe verificarse en caso de que no funcione.


In [ ]:
%%writefile Controlador.m
clear all; clc;
setenv PYTHON /usr/bin/python %Acá está el vinculo con Pyton, para acceder al sympy desde symbolic
%/usr/bin/python
pkg load symbolic %Primera vez que se corre el paquete simbólico de Python. 
syms fi fi_p fi_pp p p_p p_pp M m u long Fricc g; 
disp('Para el equilibrio inestable') 
ang_inic=0; 
p_pp=(1/(M+m))*(u-m*long*fi_pp+m*long*fi_p^2*fi-Fricc*p_p); %Pequeños angulos 
% fi_pp_=(1/long)*(g*sin(fi)-p_pp*cos(fi));%Expresión completa 
% fi_pp=(1/long)*(g*(fi)-p_pp); %Pequeños angulos para fi~0, sin(fi)~fi, cos(fi)~1 
fi_pp=solve(fi_pp==(1/long)*(g*fi-p_pp),fi_pp); 
%disp('fi_pp='); pretty(simplify(fi_pp)); 
p_pp=subs(p_pp,'fi_pp',fi_pp); 
%disp('p_pp='); pretty(simplify(p_pp)) 
Mat_A=[[0 1 0 0]; 
[subs(subs(subs(subs(diff(p_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
[0 0 0 1]; 
[subs(subs(subs(subs(diff(fi_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]]; 
Mat_B=[0; 
subs(subs(subs(subs(diff(p_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0);... 
0; 
subs(subs(subs(subs(diff(fi_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
disp('A=')
pretty(simplify(Mat_A)) 
disp('B=')
pretty(simplify(Mat_B))
syms Mat_C;
Mat_C=[[1 0 0 0];[0 0 1 0]];
disp('C=')
(Mat_C)
disp('D=0')

Overwriting Controlador.m


In [ ]:
# -W : no window system
!octave -W Controlador.m

OctSymPy v2.6.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 3935) might appear next.
Python 2.7.17 (default, Mar 18 2022, 13:21:42) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> 
OctSymPy: Communication established.  SymPy v1.1.1.
Para el equilibrio inestable
A=
  ⎡0     1         0      0⎤
  ⎢                        ⎥
  ⎢   -Fricc     -g⋅m      ⎥
  ⎢0  ───────    ─────    0⎥
  ⎢      M         M       ⎥
  ⎢                        ⎥
  ⎢0     0         0      1⎥
  ⎢                        ⎥
  ⎢   Fricc    g⋅(M + m)   ⎥
  ⎢0  ──────   ─────────  0⎥
  ⎣   M⋅long     M⋅long    ⎦
B=
  ⎡  0   ⎤
  ⎢      ⎥
  ⎢  1   ⎥
  ⎢  ─   ⎥
  ⎢  M   ⎥
  ⎢      ⎥
  ⎢  0   ⎥
  ⎢      ⎥
  ⎢ -1   ⎥
  ⎢──────⎥
  ⎣M⋅long⎦
C=
Mat_C =

   1   0   0   0
   0   0   1   0

D=0



Se desea obtener mediante cálculo simbólico la versión lineal del péndulo en el equilibrio estable. Se emplea Taylor previo reemplazo de cos(𝛷) ≈-1 y sen(𝛷)≈-𝛷. Luego se presenta el sistema matricial.


In [3]:
%%writefile Controlador.m
clear all; clc;
setenv PYTHON /usr/bin/python %Acá está el vinculo con Pyton, para acceder al sympy desde symbolic
%/usr/bin/python
pkg load symbolic %Primera vez que se corre el paquete simbólico de Python. 
syms fi fi_p fi_pp p p_p p_pp M m u long Fricc g; 
disp('Para el equilibrio estable') 
ang_inic=pi; 
p_pp=(1/(M+m))*(u+m*long*fi_pp-m*long*fi_p^2*fi-Fricc*p_p); %Pequeños angulos 
% fi_pp_=(1/long)*(-g*sin(fi)+p_pp*cos(fi));%Expresión completa 
% fi_pp=(1/long)*(-g*(fi)+p_pp); %Pequeños angulos para fi~0, sin(fi)~fi, cos(fi)~-1 
fi_pp=solve(fi_pp==(1/long)*(-g*fi+p_pp),fi_pp); 
disp('fi_pp='); pretty(simplify(fi_pp)); 
p_pp=subs(p_pp,'fi_pp',fi_pp); 
%disp('p_pp='); pretty(simplify(p_pp)) 
Mat_A=[[0 1 0 0]; 
[subs(subs(subs(subs(diff(p_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
[0 0 0 1]; 
[subs(subs(subs(subs(diff(fi_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]]; 
Mat_B=[0; 
subs(subs(subs(subs(diff(p_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0);... 
0; 
subs(subs(subs(subs(diff(fi_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
disp('A=')
pretty(simplify(Mat_A)) 
disp('B=')
pretty(simplify(Mat_B))
syms Mat_C;
Mat_C=[[1 0 0 0];[0 0 1 0]];
disp('C=')
(Mat_C)
disp('D=0')

Writing Controlador.m


In [4]:
!octave -W Controlador.m

OctSymPy v2.6.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 3680) might appear next.
Python 2.7.17 (default, Mar 18 2022, 13:21:42) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> 
OctSymPy: Communication established.  SymPy v1.1.1.
Para el equilibrio estable
fi_pp=
                               2                    
  -Fricc⋅p_p - M⋅fi⋅g - fi⋅fi_p ⋅long⋅m - fi⋅g⋅m + u
  ──────────────────────────────────────────────────
                        M⋅long                      
A=
  ⎡0     1          0       0⎤
  ⎢                          ⎥
  ⎢   -Fricc      -g⋅m       ⎥
  ⎢0  ───────     ─────     0⎥
  ⎢      M          M        ⎥
  ⎢                          ⎥
  ⎢0     0          0       1⎥
  ⎢                          ⎥
  ⎢   -Fricc   -g⋅(M + m)    ⎥
  ⎢0  ───────  ───────────  0⎥
  ⎣    M⋅long     M⋅long     ⎦
B=
  ⎡  0